version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.6
    container_name: kibana
    expose:
      - 5601
    ports:
      - "5601:5601"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    expose:
      - 9200
      - 9300
    ports:
      - "9200:9200"
